# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/
# 

#     show_in_project_view: false # ou show_in_blog_post_view: false
#     # ...

# Appearance
# https://wowchemy.com/docs/getting-started/customization/



appearance:
  theme_day: minimal
  theme_night: minimal
  font: Native
  font_size: L
   
# SEO

marketing:
  seo:
    site_type: "LocalBusiness"
    local_business_type: "ProfessionalService"
    org_name: 'EMAGE.Diag'
    description: 'Analyses de vos données, enquêtes et conseils en communication. Another French data-scientist website.'
  analytics:
    google_analytics: 'G-BE4TGDH8NC'
    google_optimize: true
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    leftsidebar: false
    align: l
    show_logo: true
    # Display your site title or `assets/media/logo*` image in the nav bar?
    show_language: true
    show_day_night: false
    show_search: true
    # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
    highlight_active_link: true

# Site footer

footer:
  block: minimal
  show_translations: true
  copyright:
    notice: '© {year} Clément L.' # '{license}' tu à ce genre de shortcode si tu veux
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false 
      # vérifier ce que c'est que ça "allow_commercial"

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/Clement-LVD/EMAGE'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
